version: '4.26'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_SQL;}
      MYSQL_DATABASE: dbPanaderia
      MYSQL_USER: ${USER_SQL;}
      MYSQL_PASSWORD: ${PASSWORD_SQL;}
    ports:
      - "3307:3307"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
